export default {
  data: [
    {
      id: 1,
      name: {
        uz: "3.1. Kirish ta'qiqlangan",
        ru: '3.1. Не входить',
        kiril: '3.1. Кириш таъқиқланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/1.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 2,
      name: {
        uz: "3.2. Harakatlanish ta'qiqlangan",
        ru: '3.2. Движение запрещено',
        kiril: '3.2. Ҳаракатланиш таъқиқланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/2.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 3,
      name: {
        uz: '3.3. Mexanik transport vositalarining harakatlanishi taqiqlangan',
        ru: '3.3. Автотранспортным средствам проезд запрещен',
        kiril: '3.3. Механик транспорт воситаларининг ҳаракатланиши тақиқланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/3.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 4,
      name: {
        uz: '3.4. Yuk avtomobillarining harakatlanishi taqiqlangan',
        ru: '3.4. Движение грузовых автомобилей запрещено.',
        kiril: '3.4. Юк автомобилларининг ҳаракатланиши тақиқланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/4.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 5,
      name: {
        uz: '3.5. Mototsikllar harakatlanishi taqiqlangan',
        ru: '3.5. Мотоциклы не допускаются.',
        kiril: '3.5. Мотоцикллар ҳаракатланиши тақиқланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/5.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 6,
      name: {
        uz: '3.5.1 Skuter va mopedlar harakatlanishi taqiqlangan',
        ru: '3.5.1 Движение скутеров и мопедов запрещено.',
        kiril: '3.5.1 Скутерлар ва мопедлар ҳаракатланиши тақиқланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/6.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 7,
      name: {
        uz: '3.6. Traktorlar harakatlanishi taqiqlangan',
        ru: '3.6. Движение тракторов запрещено.',
        kiril: '3.6. Тракторлар ҳаракатланиши тақиқланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/7.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 8,
      name: {
        uz: '3.7. Tirkama bilan harakatlanish taqiqlangan',
        ru: '3.7. Запрещено ездить на прицепе.',
        kiril: '3.7. Тиркама билан ҳаракатланиш тақиқланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/8.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 9,
      name: {
        uz: '3.8. Ot-arava harakatlanishi taqiqlangan',
        ru: '3.8. Конные перевозки запрещены.',
        kiril: '3.8. От-арава ҳаракатланиши тақиқланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/9.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 10,
      name: {
        uz: "3.9. Velosipedda harakatlanish ta'qiqlangan",
        ru: '3.9. Езда на велосипеде запрещена',
        kiril: '3.9. Велосипедда ҳаракатланиш таъқиқланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/10.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 11,
      name: {
        uz: "3.10. Piyodalarning harakatlanishi ta'qiqlangan",
        ru: '3.10. Движение пешеходов запрещено',
        kiril: '3.10. Пиёдаларнинг ҳаракатланиши таъқиқланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/11.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 12,
      name: {
        uz: '3.11. Vazn cheklangan',
        ru: '3.11. Вес ограничен',
        kiril: '3.11. Вазн чекланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/12.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 13,
      name: {
        uz: '3.12. O‘qqa tushadigan og‘irlik cheklangan',
        ru: '3.12. Допустимая нагрузка на ось',
        kiril: '3.12. Ўққа тушадиган оғирлик чекланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/13.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 14,
      name: {
        uz: '3.13. Cheklangan balandlik',
        ru: '3.13. Ограниченная высота',
        kiril: '3.13. Чекланган баландлик',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/14.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 15,
      name: {
        uz: '3.14. Cheklangan kenglik',
        ru: '3.14. Ограниченная ширина',
        kiril: '3.14. Чекланган кенглик',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/15.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 16,
      name: {
        uz: '3.15. Cheklangan uzunlik',
        ru: '3.15. Ограниченная длина',
        kiril: '3.15. Чекланган узунлик',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/16.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 17,
      name: {
        uz: '3.16. Eng kam oraliq',
        ru: '3.16. Минимальный интервал',
        kiril: '3.16. Энг кам оралиқ',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/17.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 18,
      name: {
        uz: '3.17.1. Bojxona',
        ru: '3.17.1. Обычаи',
        kiril: '3.17.1. Божхона',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/18.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 19,
      name: {
        uz: '3.17.2. Xavf-xatar',
        ru: '3.17.2. Риск',
        kiril: '3.17.2. Хавф-хатар',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/19.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 20,
      name: {
        uz: '3.17.3. Nazorat joy',
        ru: '3.17.3. Контрольный пункт',
        kiril: '3.17.3. Назорат жой',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/20.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 21,
      name: {
        uz: "3.18.1. O’ngga burilish ta'qiqlanadi",
        ru: '3.18.1. Поворот направо запрещен',
        kiril: '3.18.1. Ўнгга бурилиш таъқиқланади',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/21.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 22,
      name: {
        uz: '3.18.2. Chapga burilish taqiqlanadi',
        ru: '3.18.2. Поворот налево запрещен',
        kiril: '3.18.2. Чапга бурилиш тақиқланади',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/22.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 23,
      name: {
        uz: "3.19. Qayrilish ta'qiqlanadi",
        ru: '3.19. Переворачивание запрещено',
        kiril: '3.19. Қайрилиш таъқиқланади',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/23.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 24,
      name: {
        uz: '3.20. Quvib o’tish taqiqlanadi',
        ru: '3.20. Обгон запрещен',
        kiril: '3.20. Қувиб ўтиш тақиқланади',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/24.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 25,
      name: {
        uz: "3.21. Quvib o’tish ta'qiqlangan hududning oxiri",
        ru: '3.21. Конец запретной зоны',
        kiril: '3.21. Қувиб ўтиш тақиқланган ҳудуднинг охири',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/25.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 26,
      name: {
        uz: '3.22. Yuk avtomobillarida quvib o’tish taqiqlangan',
        ru: '3.22. Запрещено преследовать грузовики',
        kiril: '3.22. Юк автомобилларида қувиб ўтиш тақиқланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/26.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 27,
      name: {
        uz: '3.23. Yuk avtommobillarida quvib o’tish taqiqlangan hududning oxiri',
        ru: '3.23. Конец зоны, где запрещено преследовать грузовики',
        kiril: '3.23. Юк автоммобилларида қувиб ўтиш тақиқланган ҳудуднинг охири',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/27.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 28,
      name: {
        uz: '3.24. Yuqori tezlik cheklangan',
        ru: '3.24. Высокая скорость ограничена',
        kiril: '3.24. Юқори тезлик чекланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/28.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 29,
      name: {
        uz: '3.25. Yuqori tezlik cheklangan hududning oxiri',
        ru: '3.25. Конец зоны с ограниченным доступом к высокой скорости',
        kiril: '3.25. Юқори тезлик чекланган ҳудуднинг охири',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/29.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 30,
      name: {
        uz: "3.26. Tovuch moslamalaridan foydalanish ta'qiqlangan",
        ru: '3.26. Запрещается использование приборов для курицы.',
        kiril: '3.26. Товуч мосламаларидан фойдаланиш таъқиқланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/30.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 31,
      name: {
        uz: '3.27. To’xtash taqiqlangan',
        ru: '3.27. Парковка запрещена',
        kiril: '3.27. Тўхташ тақиқланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/31.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 32,
      name: {
        uz: "3.28. To’xtab turish ta'qiqlangan",
        ru: '3.28. Парковка запрещена',
        kiril: '3.28. Тўхтаб туриш таъқиқланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/32.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 33,
      name: {
        uz: '3.29. Oyning toq kunlarida to’xtab turish taqiqlanadi',
        ru: '3.29. Запрещено останавливаться в нечетные дни месяца.',
        kiril: '3.29. Ойнинг тоқ кунларида тўхтаб туриш тақиқланади',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/33.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 34,
      name: {
        uz: '3.30. Oyning juft kunlarida to’xtab turish taqiqlanadi',
        ru: '3.30. Запрещено останавливаться в два дня месяца.',
        kiril: '3.30. Ойнинг жуфт кунларида тўхтаб туриш тақиқланади',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/34.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 35,
      name: {
        uz: '3.31. Barcha cheklovlarning oxiri',
        ru: '3.31. Конец всех ограничений',
        kiril: '3.31. Барча чекловларнинг охири',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/35.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 36,
      name: {
        uz: "3.32. Xavfli yuklarga ega transport vositalarining harakati ta'qiqlanadi",
        ru: '3.32. Движение автотранспорта с опасными грузами запрещено.',
        kiril: '3.32. Хавфли юкларга эга транспорт воситаларининг ҳаракати таъқиқланади',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/36.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 37,
      name: {
        uz: "3.33. Portlovchi va yonuvchan yuklarga ega transport vositalarining harakatlanishi ta'qiqlanadi",
        ru: '3.33. Запрещается движение транспортных средств с взрывоопасными и легковоспламеняющимися грузами.',
        kiril:
          '3.33. Портловчи ва ёнувчан юкларга эга транспорт воситаларининг ҳаракатланиши таъқиқланади',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/37.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
    {
      id: 38,
      name: {
        uz: '3.34. Individual harakatlanish vositalarini boshqarish taqiqlangan',
        ru: '3.34. Управление индивидуальными средствами передвижения запрещено.',
        kiril: '3.34. Индивидуал ҳаракатланиш воситаларини бўшқариш тақиқланган',
      },
      img: 'https://boosimgproduct.netlify.app/signs/taqiqlovchi/38.png',
      category_id: 3,
      category_name: 'Taqiqlovchi belgilar',
    },
  ],
}
