export default {
  data: [
    {
      id: 1,
      name: {
        uz: "1.1. Shlagbaumli temir yo'l kesishmasi",
        ru: '1.1. Барьерный железнодорожный переезд',
        kiril: '1.1. Шлагбаумли темир йўл кесишмаси',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/1.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 2,
      name: {
        uz: '1.2. Shlagbaumsiz temir yo’l kesishmasi',
        ru: '1.2. Железнодорожный переезд без шлагбаумов',
        kiril: '1.2. Шлагбаумсиз темир йўл кесишмаси',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/2.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 3,
      name: {
        uz: '1.3.1. Bir izli temir yo’l',
        ru: '1.3.1. Однопутная железная дорога',
        kiril: '1.3.1. Бир изли темир йўл ',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/3.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 4,
      name: {
        uz: '1.3.2. Ko’p izli temir yo’l',
        ru: '1.3.2. Многоколейная железная дорога',
        kiril: '1.3.2. Кўп изли темир йўл',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/4.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 5,
      name: {
        uz: '1.4.1. Temir yo’l kesishmasining yaqinligi haqida ogohlantirish: O‘ng 150m',
        ru: '1.4.1. Предупреждение о железнодорожном переезде: Право 150м',
        kiril: '1.4.1. Темир йўл кесишмасининг яқинлиги ҳақида огоҳлантириш: Ўнг 150м ',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/5.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 6,
      name: {
        uz: '1.4.2. Temir yo’l kesishmasining yaqinligi haqida ogohlantirish: O‘ng 100m ',
        ru: '1.4.2. Предупреждение о железнодорожном переезде: Право 100м ',
        kiril: '1.4.2. Темир йўл кесишмасининг яқинлиги ҳақида огоҳлантириш: Ўнг 100м ',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/6.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 7,
      name: {
        uz: '1.4.2. Temir yo’l kesishmasining yaqinligi haqida ogohlantirish: O‘ng 50m ',
        ru: '1.4.3. Предупреждение о железнодорожном переезде: Право 50м ',
        kiril: '1.4.3. Темир йўл кесишмасининг яқинлиги ҳақида огоҳлантириш: Ўнг 50м ',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/7.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 8,
      name: {
        uz: '1.4.4. Temir yo’l kesishmasining yaqinligi haqida ogohlantirish: Сhap 150m ',
        ru: '1.4.4. Предупреждение о железнодорожном переезде: Лево 150м ',
        kiril: '1.4.4. Темир йўл кесишмасининг яқинлиги ҳақида огоҳлантириш: Чап 150м ',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/10.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 9,
      name: {
        uz: '1.4.5. Temir yo’l kesishmasining yaqinligi haqida ogohlantirish: Сhap 100m ',
        ru: '1.4.5. Предупреждение о железнодорожном переезде: Лево 100м ',
        kiril: '1.4.5. Темир йўл кесишмасининг яқинлиги ҳақида огоҳлантириш: Чап 100м ',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/9.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 10,
      name: {
        uz: '1.4.6. Temir yo’l kesishmasining yaqinligi haqida ogohlantirish: Сhap 50m ',
        ru: '1.4.6. Предупреждение о железнодорожном переезде: Лево 50м ',
        kiril: '1.4.6. Темир йўл кесишмасининг яқинлиги ҳақида огоҳлантириш: Чап 50м ',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/8.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 11,
      name: {
        uz: '1.5. Tramvay yo’li bilan kesishuv',
        ru: '1.5. Трамвайный переход',
        kiril: '1.5. Трамвай йўли билан кесишув',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/11.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 12,
      name: {
        uz: '1.6. Teng ahamiyatli yo’llar kesishuvi',
        ru: '1.6. Не менее важные перекрестки',
        kiril: '1.6. Тенг аҳамиятли йўллар кесишуви',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/12.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 13,
      name: {
        uz: '1.7. Aylanma harakatlanish bilan kesishuv',
        ru: '1.7. Пересечение с вращательным движением',
        kiril: '1.7. Айланма ҳаракатланиш билан кесишув',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/13.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 14,
      name: {
        uz: '1.8. Svetofor tartibga soladi',
        ru: '1.8. Светофор регулирует',
        kiril: '1.8. Светофор тартибга солади',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/14.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 15,
      name: {
        uz: '1.9. Ko’tarma ko’prik',
        ru: '1.9. Подъемный мост',
        kiril: '1.9. Кўтарма кўприк',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/15.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 16,
      name: {
        uz: '1.10. Sohilga chiqish',
        ru: '1.10. Собираться на пляж',
        kiril: '1.10. Соҳилга чиқиш',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/16.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 17,
      name: {
        uz: "1.11.1. Xavfli burilish o'ngga",
        ru: '1.11.1. Опасный поворот направо',
        kiril: '1.11.1. Хавфли бурилиш ўнгга',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/17.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 18,
      name: {
        uz: '1.11.2. Xavfli burilish chapga',
        ru: '1.11.2. Опасный поворот налево',
        kiril: '1.11.2. Хавфли бурилиш чапга',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/18.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 19,
      name: {
        uz: '1.12.1. Xavfli burilishlar: birinchi o‘ngga, so‘ng chapga',
        ru: '1.12.1. Опасные повороты: сначала направо, потом налево',
        kiril: '1.12.1. Хавфли бурилишлар: биринчи ўнгга, сўнг чапга',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/19.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 20,
      name: {
        uz: '1.12.2. Xavfli burilishlar: birinchi chapga, so‘ng o‘ngga',
        ru: '1.12.2. Опасные повороты: сначала налево, потом направо',
        kiril: '1.12.2. Хавфли бурилишлар: биринчи чапга, сўнг ўнгга',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/20.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 21,
      name: {
        uz: '1.13. Tik nishablik',
        ru: '1.13. Крутой склон',
        kiril: '1.13. Тик нишаблик',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/21.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 22,
      name: {
        uz: '1.14. Tik balandlik',
        ru: '1.14. Крутая высота',
        kiril: '1.14. Тик баландлик',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/22.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 23,
      name: {
        uz: '1.15. Sirpanchiq yo’l',
        ru: '1.15. Это скользкая дорожка',
        kiril: '1.15. Сирпанчиқ йўл',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/23.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 24,
      name: {
        uz: '1.16. Notekis yo’l',
        ru: '1.16. Дорога грубая',
        kiril: '1.16. Нотекис йўл',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/24.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 25,
      name: {
        uz: '1.17. Tosh otilish xavfi',
        ru: '1.17. Риск бросания камней',
        kiril: '1.17. Тош отилиш хавфи',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/25.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 26,
      name: {
        uz: '1.18.1. Yo’lning torayishi',
        ru: '1.18.1. Дорога сужается',
        kiril: '1.18.1. Йўлнинг торайиши',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/26.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 27,
      name: {
        uz: "1.18.2. Yo’lning torayishi o'ngdan",
        ru: '1.18.2. Дорога сужается справа',
        kiril: '1.18.2. Йўлнинг торайиши ўнгдан',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/27.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 28,
      name: {
        uz: '1.18.3. Yo’lning torayishi chapdan',
        ru: '1.18.3. Дорога сужается слева',

        kiril: '1.18.3. Йўлнинг торайиши чапдан',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/28.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 29,
      name: {
        uz: '1.19. Ikki tomonlama harakatlanish',
        ru: '1.19. Двустороннее движение',
        kiril: '1.19. Икки томонлама ҳаракатланиш',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/29.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 30,
      name: {
        uz: '1.20. Piyodalar o’tish joyi',
        ru: '1.20. Пешеходный переход',
        kiril: '1.20. Пиёдалар ўтиш жойи',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/30.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 31,
      name: {
        uz: '1.21. Bolalar',
        ru: '1.21. Дети',
        kiril: '1.21. Болалар',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/31.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 32,
      name: {
        uz: '1.22. Velosiped yo’lkasi bilan kesishuv',
        ru: '1.22. Переход по велосипедной дорожке',
        kiril: '1.22. Велосипед йўлкаси билан кесишув',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/32.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 33,
      name: {
        uz: '1.23. Ta’mirlash ishlari',
        ru: '1.23. Ремонт',
        kiril: '1.23. Таъмирлаш ишлари',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/33.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 34,
      name: {
        uz: '1.24. Mol haydab o’tish',
        ru: '1.24. Вождение',
        kiril: '1.24. Мол ҳайдаб ўтиш',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/34.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 35,
      name: {
        uz: '1.25.1 Yovvoyi hayvonlar',
        ru: '1.25.1 Дикие животные',
        kiril: '1.25.1 Ёввойи ҳайвонлар',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/35.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 36,
      name: {
        uz: '1.25.2 Pastlarb uchuvchi qushlar',
        ru: '1.25.2 Низколетающие птицы',
        kiril: '1.25.2 Пастларб учувчи қушлар',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/36.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 37,
      name: {
        uz: '1.25.3 Kemiruvchi va sudralib yuruvchi hayvonlar',
        ru: '1.25.3 Грызуны и пресмыкающиеся животные',
        kiril: '1.25.3 Кемирувчи ва судралиб юрувчи ҳайвонлар',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/37.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 38,
      name: {
        uz: '1.26. Toshlar tushishi',
        ru: '1.26. Падающие камни',
        kiril: '1.26. Тошлар тушиши',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/38.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 39,
      name: {
        uz: '1.27. Yonlama shamol',
        ru: '1.27. Направленный ветер',
        kiril: '1.27. Ёнлама шамол',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/39.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 40,
      name: {
        uz: '1.28. Pastlab uchuvchi samolyotlar',
        ru: '1.28. Замедление самолетов',
        kiril: '1.28. Пастлаб учувчи самолётлар',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/40.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 41,
      name: {
        uz: '1.29. Tonnel',
        ru: '1.29. Тоннель',
        kiril: '1.29. Тоннел',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/41.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 42,
      name: {
        uz: '1.30. Boshqa xavf-xatar',
        ru: '1.30. Прочие риски',
        kiril: '1.30. Бошқа хавф-хатар',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/42.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 43,
      name: {
        uz: "1.31. Sun'iy yo'l notekisliklari",
        ru: '1.31. Искусственная неровность дороги',
        kiril: '1.31. Сунъий йўл нотекисликлари',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/43.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 44,
      name: {
        uz: "1.31.1. Burilishning yo’nalishi o'ngga",

        ru: '1.31.1. Направление вращения направо',
        kiril: '1.31.1. Бурилишнинг йўналиши ўнгга',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/44.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 45,
      name: {
        uz: '1.31.2. Burilishning yo’nalishi chapga',
        ru: '1.31.2. Направление вращения налево',
        kiril: '1.31.2. Бурилишнинг йўналиши чапга',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/45.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 46,
      name: {
        uz: "1.31.3. Burilishning yo’nalishi chapga va o'ngga",
        ru: '1.31.3. Направление вращения налево и направо',
        kiril: '1.31.3. Бурилишнинг йўналиши чапга ва ўнгга',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/46.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 47,
      name: {
        uz: '1.32. Tirbandlik',
        ru: '1.32. Скопление',
        kiril: '1.32. Тирбандлик',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/47.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 48,
      name: {
        uz: '1.33. Qatnov qismi kesishmasi hududi',
        ru: '1.33. Зона пересечения проезжей части',
        kiril: '1.33. Қатнов қисми кесишмаси ҳудуди',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/48.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 49,
      name: {
        uz: "1.34. Diqqat boshqariladigan to'siq",
        ru: '1.34. Внимание, управляемое заграждение',
        kiril: '1.34. Диққат бошқариладиган тўсиқ',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/49.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
    {
      id: 50,
      name: {
        uz: '1.34. Piyodalarning yo‘l yoqasidan yurish mumkin bo‘lgan hudud',
        ru: '1.34. Зона, где пешеходам разрешено движение по обочине',
        kiril: '1.34. Пиёдаларнинг йўл ёқасидан юриш мумкин бўлган ҳудуд',
      },
      img: 'https://boosimgproduct.netlify.app/signs/ogoxlantiruvchi/50.png',
      category_id: 1,
      category_name: 'ogoxlantiruvchi belgilar',
    },
  ],
}
